export const SET_ALL_PROJECTS_OVERLAY = "SET_ALL_PROJECTS_OVERLAY";
export const SET_ALL_POSTS_OVERLAY = "SET_ALL_POSTS_OVERLAY";
export const SET_CREATE_CATEGORY_OVERLAY = "SET_CREATE_CATEGORY_OVERLAY";

export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const GET_CATEGORIES = "GET_CATEGORIES";